import Image from 'next/image'
import { staticPath } from '../../lib/$path'

export const Saiun = () => (
  <section className="result saiun">
    <div className="inner">
      <h3>
        <div className="heading_icon">
          <Image src={staticPath.images.suimei.peach_svg} className="image" fill alt="桃のアイコン"></Image>
        </div>
        <div>歳運</div>
      </h3>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>
              天干<br className="header_br_sp"></br>通変星
            </th>
            <th>大運</th>
            <th>蔵干</th>
            <th>
              蔵干<br className="header_br_sp"></br>通変星
            </th>
            <th>十二運</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>
              <span>30歳</span>2017年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>31歳</span>2018年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>32歳</span>2019年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>33歳</span>2020年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>34歳</span>2021年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr className="current">
            <th>
              <span>35歳</span>2022年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>36歳</span>2023年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>37歳</span>2024年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>38歳</span>2025年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>39歳</span>2026年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
          <tr>
            <th>
              <span>40歳</span>2027年
            </th>
            <td>比肩</td>
            <td>戊午</td>
            <td>養</td>
            <td>戊</td>
            <td>偏印</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
)
